### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by rajikaimal** [99xt/react-scaffolder#15]
Design a logo

**Comment by isuruAb** [comment]
@rajikaimal  which logo i need to add ? is there any separate logo for react-scaffoldder

**Comment by rajikaimal** [comment]
Title was misleading. Changed the title. This is about designing a logo for react-scaffolder.

**Comment by isuruAb** [comment]
@rajikaimal  please check this
![logo](https://user-images.githubusercontent.com/7692626/29900165-890139d0-8e0d-11e7-831d-ffd027580456.png)

**Comment by rajikaimal** [comment]
Looks good, @charithsoori Any thoughts ?

**Comment by isuruAb** [comment]
check this one also
![logo2](https://user-images.githubusercontent.com/7692626/29908100-365d11e2-8e3d-11e7-833c-8ac9b9e086d9.png)
