### ISSUE TITLE
ReferenceError: init is not defined at react init myApp

### ISSUE THREAD

**Issue by rafaelklaessen** [99xt/react-scaffolder#16]
### expected behaviour
√ application created successfully
### steps to reproduce the problem.
Install react-scaffolder globally and run react init myApp
### specifications like the version of the project, operating system, or hardware.
v0.3.0
### fix
The error occurs because in bin/initialize.js at rule 14 init is declared without the let/const/var keyword. I've changed it to var and it worked fine.

**Comment by rafaelklaessen** [comment]
I can fix it while I'm porting to ES6. Should I do this?

**Comment by rajikaimal** [comment]
This is a problem with your Node.js version, if you upgrade to v6.0, this won't happen. This is a minimum requirement for this tool.

https://nodejs.org/en/docs/es6/

**Comment by rafaelklaessen** [comment]
But I have Node.js v7.0.
The error occurs because node thinks you are overriding the init variable that has already been defined (because there isn't a var/let/const keyword before it), while you are trying to define the init variable globally. As said, adding var/let/const gets it working.

**Comment by rajikaimal** [comment]
Since this have been fixed, closing this issue now.
