### ISSUE TITLE
[Enhancement] Replace init command template

### ISSUE THREAD

**Issue by rajikaimal** [99xt/react-scaffolder#21]
Replace [react-boilerplate](https://github.com/99xt/react-boilerplate) (code generated with `init` command) with [create-react-app](https://github.com/facebookincubator/create-react-app) boilerplate.

**Comment by isuruAb** [comment]
@rajikaimal  could you please explain some more about the issue and what need to be done here ??

**Comment by rajikaimal** [comment]
My idea was to let the user provide a URL to a boilerplate repository that they prefer and initialize a project with that. For an example 

```
react init awesome-project https://github.com/react-boilerplate/react-boilerplate
```
will initialize the project from this boilerplate not the default one we have right now,
or else we can give an option to choose CRA boilerplate as well.

**Comment by isuruAb** [comment]
working on this

**Comment by rajikaimal** [comment]
Nice
