### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by pattiereaves** [99xt/react-scaffolder#29]
### expected behaviour
After running 

```
npm install -g react-scaffolder
react v -c
```

I get the error
```
env: node\r: No such file or directory
```

### steps to reproduce the problem.

See above

### specifications like the version of the project, operating system, or hardware.

I'm running npm@5.1.0 and node@6.10.3 on macOS@10.12.5

**Comment by rajikaimal** [comment]
Hi, did you follow the [quick start guide](https://github.com/99xt/react-scaffolder#quick-start) ?

**Comment by rajikaimal** [comment]
First you should create a project with `init` command, or you should use the CLI with an existing project by configuring `.reactclirc` file

**Comment by rajikaimal** [comment]
@pattiereaves Since I couldn't reproduce this, I'll close this for now. If you come up with any way to reproduce this, please feel free to reopen the issue.

**Comment by zaguiini** [comment]
+1
