### ISSUE TITLE
react init command doesn't work

### ISSUE THREAD

**Issue by isuruAb** [99xt/react-scaffolder#33]
### expected behaviour
According to the documentation it should create a new project from this command
`react init projectname
`
### steps to reproduce the problem.

It gives this error on CLI
```
isuruAb:github isuruAb$ react init awesome-project
env: node\r: No such file or directory
```

### specifications like the version of the project, operating system, or hardware.

macOS Sierra 10.12.5

**Comment by isuruAb** [comment]
I resolved this problem by Re installing node by 
`brew uninstall node
`and re installing it 
`brew install node`


if above solution doesn't work for you, please check thisout.
https://gist.github.com/DanHerbert/9520689

**Comment by rajikaimal** [comment]
This is great @isuruAb shall we close this issue then ?
