### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by rajikaimal** [99xt/react-scaffolder#38]
Improve error messages in case of exceptions.

- Trying to use an existing directory name to create a project.
- Overwriting existing file names.

**Comment by isuruAb** [comment]
working on this

**Comment by rajikaimal** [comment]
Since this is not fully resolved.

**Comment by isuruAb** [comment]
@rajikaimal  can you explain a scenario that i can check the second point "Overwriting existing file names."

**Comment by rajikaimal** [comment]
If we use `generate` with an existing file name, it should provide a meaningful error message.
