### ISSUE TITLE
Clarify the issue or the feature that's going to be implemented

### ISSUE THREAD

**Issue by shapkarin** [99xt/react-scaffolder#53]
And as CONTRIBUTING.md says "Clarify the issue or the feature that's going to be implemented" 

- [x] Add default config if user don't have ".reactclirc"
- [x] Count props, don't ask user about a number
- [x] Remove filename postfix ".react.js"

Also maybe I'll add some features for redux.

I do not agree with name like parent or child, but I like format that you use to store templates and interactive cli.

**Comment by rajikaimal** [comment]
Can you try looking at the latest changes? I've made a few in the master branch.

**Comment by shapkarin** [comment]
Cool, seem that I removed my comment about that 🙂

**Comment by rajikaimal** [comment]
About 'count props', what's your suggestion here

**Comment by shapkarin** [comment]
Cli asking about number of props. I don't like that.. So count them somehow. I didn't thought how but like just define them for a start with cli arguments prop1 prop2 prop3 then asking fir a type or even with types already prop:type. Also I want to rename parent and child and add other templates to that list.

**Comment by shapkarin** [comment]
I plan to rename Parent and Child and remove postfix by default but with possibility to add by config file. Are you OK with that?

**Comment by rajikaimal** [comment]
I think we don't need any prefixes according to current practices we don't use prefixes in react component files.

**Comment by rajikaimal** [comment]
> Cli asking about number of props. I don't like that.. So count them somehow. I didn't thought how but like just define them for a start with cli input prop1 prop2 prop3 then asking for an each type or even with types already prop:type.

How do we stop adding the props, if we don't know how many there are?

**Comment by rajikaimal** [comment]
Perhaps ask the user after adding each prop to proceed to the next step?

**Comment by shapkarin** [comment]
No. I mean we can ask to input all props before you define types, then count words in string separated by space and then to ask type for each. For example to make array like:
```javascript
'prop1 prop2 prop3'.split(' ')
```

**Comment by shapkarin** [comment]
No. I mean we can ask to input all props before you define types, then count words in string separated by space and then to ask type for each. For example to make array like:
```
const props = prop1 prop2 prop3'.split(' ')
const count = props.length
```

**Comment by shapkarin** [comment]
No. I mean we can ask to input all props before you define types, then count words in string separated by space and then to ask type for each. For example to make array like:
```
const props = "prop1 prop2 prop3".split(" ")
const count = props.length
```

**Comment by shapkarin** [comment]
No. I mean we can ask to input all props before you define types, then count words in string separated by space and then to ask type for each. For example to make array like:
```es6
const props = "prop1 prop2 prop3".split(" ")
const count = props.length
```

**Comment by rajikaimal** [comment]
Great, can you send a PR for this?

**Comment by shapkarin** [comment]
Sure I will.

**Comment by shapkarin** [comment]
@rajikaimal I add some todos to the list.

**Comment by shapkarin** [comment]
@rajikaimal OK, I'll create other issues for other changes.
